In [2]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/mehrib5wxi5mqovwtgyt3hpzdnllyp')
df

,league,player_id,salary,season,season_end,season_start,team
0,NBA,abdelal01,395000,1990-91,1991,1990,Portland Trail Blazers
1,NBA,abdelal01,494000,1991-92,1992,1991,Portland Trail Blazers
2,NBA,abdelal01,500000,1992-93,1993,1992,Boston Celtics
3,NBA,abdelal01,805000,1993-94,1994,1993,Boston Celtics
4,NBA,abdelal01,650000,1994-95,1995,1994,Sacramento Kings
...,...,...,...,...,...,...,...
14158,NBA,zipsepa01,750000,2016-17,2017,2016,Chicago Bulls
14159,NBA,zipsepa01,1312611,2017-18,2018,2017,Chicago Bulls
14160,NBA,zizican01,1645200,2017-18,2018,2017,Cleveland Cavaliers
14161,NBA,zubaciv01,1034956,2016-17,2017,2016,Los Angeles Lakers
14162,NBA,zubaciv01,1312611,2017-18,2018,2017,Los Angeles Lakers

In [3]:
df_players = pd.read_csv('datadavis-nba-salaries_players.csv')


df_players[df_players['name']=='Pau Gasol']

,_id,birthDate,birthPlace,career_AST,career_FG%,career_FG3%,career_FT%,career_G,career_PER,career_PTS,...,draft_pick,draft_round,draft_team,draft_year,height,highSchool,name,position,shoots,weight
1428,gasolpa01,"July 6, 1980","Barcelona, Spain",3.2,50.7,36.8,75.3,1226,21.4,17.0,...,3rd overall,1st round,Atlanta Hawks,2001,7-0,NaN,Pau Gasol,Center and Power Forward,Right,250lb

In [4]:
df_all = pd.merge(df,df_players,left_on='player_id',right_on='_id')

In [5]:
df_all.dropna(subset=['team'],inplace=True)
df_all.isnull().sum()

league             0
player_id          0
salary             0
season             0
season_end         0
season_start       0
team               0
_id                0
birthDate          0
birthPlace         0
career_AST         0
career_FG%         0
career_FG3%        0
career_FT%         0
career_G           0
career_PER         0
career_PTS         0
career_TRB         0
career_WS          0
career_eFG%        0
college         1636
draft_pick      1902
draft_round     1902
draft_team      1902
draft_year      1902
height             0
highSchool       989
name               0
position           0
shoots             0
weight             0
dtype: int64

In [7]:
df_all

,league,player_id,salary,season,season_end,season_start,team,_id,birthDate,birthPlace,...,draft_round,draft_team,draft_year,height,highSchool,name,position,shoots,weight,player_season_id
0,NBA,abdelal01,395000,1990-91,1991,1990,Portland Trail Blazers,abdelal01,"June 24, 1968","Cairo, Egypt",...,1st round,Portland Trail Blazers,1990,6-10,"Bloomfield in Bloomfield, New Jersey",Alaa Abdelnaby,Power Forward,Right,240lb,Alaa AbdelnabyPortland Trail Blazers1990-91
1,NBA,abdelal01,494000,1991-92,1992,1991,Portland Trail Blazers,abdelal01,"June 24, 1968","Cairo, Egypt",...,1st round,Portland Trail Blazers,1990,6-10,"Bloomfield in Bloomfield, New Jersey",Alaa Abdelnaby,Power Forward,Right,240lb,Alaa AbdelnabyPortland Trail Blazers1991-92
2,NBA,abdelal01,500000,1992-93,1993,1992,Boston Celtics,abdelal01,"June 24, 1968","Cairo, Egypt",...,1st round,Portland Trail Blazers,1990,6-10,"Bloomfield in Bloomfield, New Jersey",Alaa Abdelnaby,Power Forward,Right,240lb,Alaa AbdelnabyBoston Celtics1992-93
3,NBA,abdelal01,805000,1993-94,1994,1993,Boston Celtics,abdelal01,"June 24, 1968","Cairo, Egypt",...,1st round,Portland Trail Blazers,1990,6-10,"Bloomfield in Bloomfield, New Jersey",Alaa Abdelnaby,Power Forward,Right,240lb,Alaa AbdelnabyBoston Celtics1993-94
4,NBA,abdelal01,650000,1994-95,1995,1994,Sacramento Kings,abdelal01,"June 24, 1968","Cairo, Egypt",...,1st round,Portland Trail Blazers,1990,6-10,"Bloomfield in Bloomfield, New Jersey",Alaa Abdelnaby,Power Forward,Right,240lb,Alaa AbdelnabySacramento Kings1994-95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14158,NBA,zipsepa01,750000,2016-17,2017,2016,Chicago Bulls,zipsepa01,"February 18, 1994","Heidelberg, Germany",...,2nd round,Chicago Bulls,2016,6-8,NaN,Paul Zipser,Small Forward,Right,215lb,Paul ZipserChicago Bulls2016-17
14159,NBA,zipsepa01,1312611,2017-18,2018,2017,Chicago Bulls,zipsepa01,"February 18, 1994","Heidelberg, Germany",...,2nd round,Chicago Bulls,2016,6-8,NaN,Paul Zipser,Small Forward,Right,215lb,Paul ZipserChicago Bulls2017-18
14160,NBA,zizican01,1645200,2017-18,2018,2017,Cleveland Cavaliers,zizican01,"January 4, 1997","Split, Croatia",...,1st round,Boston Celtics,2016,6-11,NaN,Ante Zizic,Center,Right,254lb,Ante ZizicCleveland Cavaliers2017-18
14161,NBA,zubaciv01,1034956,2016-17,2017,2016,Los Angeles Lakers,zubaciv01,"March 18, 1997","Mostar, Bosnia and Herzegovina",...,2nd round,Los Angeles Lakers,2016,7-1,NaN,Ivica Zubac,Center,Right,240lb,Ivica ZubacLos Angeles Lakers2016-17
14162,NBA,zubaciv01,1312611,2017-18,2018,2017,Los Angeles Lakers,zubaciv01,"March 18, 1997","Mostar, Bosnia and Herzegovina",...,2nd round,Los Angeles Lakers,2016,7-1,NaN,Ivica Zubac,Center,Right,240lb,Ivica ZubacLos Angeles Lakers2017-18